name: CI

on:
  pull_request:
  push:

jobs:
  Test:
    runs-on: macos-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Brew
        run: brew install npm

      - name: Install dependencies
        run: make deps

      - name: Test
        run: make test

      - name: Lint
        run: make lint
